### ISSUE TITLE
Not working with RVM

### ISSUE THREAD

**Issue by loochao** [pymander/evernote-mode#23]
I tried installing one via RVM (1.9.3), got all necessary gems, yet thing is still broken. Throws this message:

 $HOME/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- oauth (LoadError)
from $HOME/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
from $HOME/.rvm/rubies/ruby-1.9.3-p551/bin/enclient.rb:40:in `<main>'

I believe all the necessary parts have been installed, for when I call enclient.rb directly in a terminal, everything works fine (to test this, I added one line at the bottom of that file: print "Succuss"), but when M-x evernote-mode, it pops up the error message above.

My guessing is still the environment, since rvm has a very long script to set the env before running, which is located at ~/.rvm/script/rvm, however when calling inside emacs, the environment variable is not set in the right way, so all the gem files like oauth are not found.

**Comment by pymander** [comment]
I've never used RVM, so my guess is that there are missing environment
variables. You might have to set them manually in your .emacs.el file.
