### ISSUE TITLE
evernote-note-open v0.2.3 always says "illegal field type  for +TX+-+Google+Search&sa"

### ISSUE THREAD

**Issue by xanalogica** [pymander/evernote-mode#32]
W, [2015-10-02T08:52:44.913794 #28691]  WARN -- : illegal field type  for +TX+-+Google+Search&sa
W, [2015-10-02T08:52:44.913915 #28691]  WARN -- : ["/usr/bin/enclient.rb:134:in `block in deserialize'", "/usr/bin/enclient.rb:94:in `each'", "/usr/bin/enclient.rb:94:in `deserialize'", "/usr/bin/enclient.rb:128:in `block in deserialize'", "/usr/bin/enclient.rb:94:in `each'", "/usr/bin/enclient.rb:94:in `deserialize'", "/usr/bin/enclient.rb:904:in `block (3 levels) in get_result_from_local_cache'", "/usr/bin/enclient.rb:902:in `each_value'", "/usr/bin/enclient.rb:902:in `block (2 levels) in get_result_from_local_cache'", "/usr/bin/enclient.rb:1396:in `open'", "/usr/bin/enclient.rb:1396:in `open_note'", "/usr/bin/enclient.rb:901:in `block in get_result_from_local_cache'", "/usr/bin/enclient.rb:1368:in `transaction'", "/usr/bin/enclient.rb:900:in `get_result_from_local_cache'", "/usr/bin/enclient.rb:891:in `exec_impl'", "/usr/bin/enclient.rb:418:in `exec'", "/usr/bin/enclient.rb:1928:in `run'", "/usr/bin/enclient.rb:1952:in `<main>'"]

**Comment by xanalogica** [comment]
I've just installed evernote-mode, from the latest Git version and when I try to *open* a file I get the above error.  However when I invoke evernote-create-note I am able to create a new note and see it on the Evernote website.  I just can never re-open it later.

**Comment by pymander** [comment]
We need to know what version of Ruby is installed on your system.

**Comment by ayman** [comment]
I'm seeing something similar:

```
illegal field type  for  :editmode 
```

The browser works, I see the tags, but if i try to open anything I see the above error with ```ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin15]```

**Comment by ayman** [comment]
Found

```lisp
((class . ErrorReply)(command_id . 6)(result_code . 101)(message . "illegal field type  for  :editmode "))
```
in  the ```*Evernote-Client-Output*``` buffer.
